### ISSUE TITLE
付费节点clash-clash 分应用-clash url代理

### ISSUE THREAD

**Issue by clashvpn9** [clashvpn9/p#4]
推荐榜单1、爱连VPN
邀请好友注册充值返利高达40-50%
注册登陆网址：（打不开请点击下面导航）https://www.iovevpn.com/#/register?code=MIGgsNCV
永久导航：（最新网址进导航页面查找）https://www.ailianvpn.com/
永久海外官网：（翻墙才能打开）https://www.iovevpn.com/
爱连VPN客户端和APP下载地址：（支持安卓-Winodws-MAC-苹果ios）https://www.ailianvpn.com/
飞机爱连VPN官方频道通知群 https://t.me/iovevpn1
有任何问题反馈永久海外邮箱：ailianvpn@gmail.com
相比直连机场更加推荐购买中转机场。中转机场机器便宜一般更加带宽大，公网主要问题是出口偶尔会绕路导致网络波动影响。专线主要是不过墙延迟低，网络波动小，专线机场日常使用体验会更丝滑更舒服。机场比的是钞能力，速度要看机场的总带宽大小。稳定要看机场的资源质量，主要是看机场主的上游的线路质量，解锁看的是机场主的落地/解锁商是否优秀。机场带宽大和稳定性最重要。

推荐榜单2、火火VPN
注册登陆网址：（打不开请点击下面导航）https://www.huohuovpn.com/#/register?code=VbaZhlak
永久导航：（最新网址进导航页面查找）https://www.huohuohuo.cloud/
永久海外官网：（翻墙才能打开）https://www.huohuovpn.com
火火加速器上線啦，高科技翻墻上網，帶你看看外面的世界 火火加速器上線啦，高科技翻墻上網，帶你看看外面的世界 網址總死總找不到，播放不了，大陸封鎖網址 ，沒關系可以用我們的高科技上網軟件，軟件使用全程SSL加密,保護你的隱私安全

#### 一、付费节点 Clash

**付费节点** 是指购买的高性能代理节点，这些节点通常提供更稳定、更快速的网络服务。以下是如何在 Clash 中配置和使用付费节点的步骤：

1. **购买付费节点**：
   - **选择服务商**：从信誉良好的服务提供商（“机场”）购买付费节点。这些服务商通常会提供高性能、稳定的节点。
   - **获取节点信息**：购买后，服务商会提供节点信息，包括服务器地址、端口、加密方法等。

2. **配置 Clash**：
   - **下载配置文件**：服务商可能会提供配置文件（如 `.yaml` 文件），你可以直接下载使用。
   - **手动添加节点**：
     - 打开 Clash 的配置文件（`config.yaml`）。
     - 添加付费节点的配置：
       ```yaml
       proxies:
         - name: "PaidNode"
           type: socks5
           server: "paid.example.com"
           port: 1080
           password: "your-password"
           method: "aes-256-gcm"
       ```
   - **配置代理组**：
     - 在 `proxy-groups` 中设置默认使用付费节点：
       ```yaml
       proxy-groups:
         - name: "Default"
           type: select
           proxies:
             - "PaidNode"
             - "AnotherNode"
       ```

3. **保存并应用**：
   - **保存文件**：保存配置文件的更改。
   - **重新加载配置**：在 Clash 客户端中重新加载配置或重启应用。

4. **验证功能**：
   - **测试连接**：确保付费节点可以正常连接，访问被限制的内容或测试网络速度。

#### 二、Clash 分应用设置

**Clash 分应用** 功能允许你为不同的应用设置不同的代理规则。这样可以实现更精细的流量管理，例如某些应用流量通过特定代理，而其他应用则使用默认的网络连接。以下是如何配置分应用代理的步骤：

1. **配置分应用规则**：
   - **编辑配置文件**：在 Clash 的 `config.yaml` 文件中设置应用分流规则。
   - **添加应用规则**：
     ```yaml
     rules:
       - PROCESS-NAME,app1.exe,Proxy
       - PROCESS-NAME,app2.exe,DIRECT
       - MATCH,Default
     ```
     在这里：
     - `PROCESS-NAME,app1.exe,Proxy`：将 `app1.exe` 的流量通过代理 `Proxy` 处理。
     - `PROCESS-NAME,app2.exe,DIRECT`：将 `app2.exe` 的流量直接连接，不经过代理。

2. **设置应用路径**：
   - **确定应用路径**：你需要知道应用的可执行文件名（如 `app1.exe`）以便配置。
   - **支持平台**：分应用功能在不同操作系统上的实现可能有所不同，确保你的平台支持该功能。

3. **保存并应用配置**：
   - **保存文件**：保存 `config.yaml` 文件的更改。
   - **重新加载配置**：在 Clash 客户端中重新加载配置或重启应用。

4. **验证分流效果**：
   - **测试应用**：确认配置的应用流量是否按照规则通过指定的代理或直接连接。

#### 三、Clash URL 代理

**Clash URL 代理** 指的是通过 Clash 配置 URL 代理规则，来处理不同 URL 的流量。以下是如何设置 URL 代理的步骤：

1. **配置 URL 代理规则**：
   - **编辑配置文件**：在 Clash 的 `config.yaml` 文件中设置 URL 代理规则。
   - **示例配置**：
     ```yaml
     rules:
       - DOMAIN-SUFFIX,example.com,Proxy
       - DOMAIN-SUFFIX,another-example.com,DIRECT
       - MATCH,Default
     ```
     在这里：
     - `DOMAIN-SUFFIX,example.com,Proxy`：将访问 `example.com` 域名的流量通过代理 `Proxy` 处理。
     - `DOMAIN-SUFFIX,another-example.com,DIRECT`：将访问 `another-example.com` 的流量直接连接。

2. **设置 URL 代理组**：
   - **配置代理组**：可以在 `proxy-groups` 中定义代理组，并在规则中使用这些组。
     ```yaml
     proxy-groups:
       - name: "ProxyGroup"
         type: select
         proxies:
           - "ProxyNode1"
           - "ProxyNode2"
     ```
   - **使用代理组**：
     ```yaml
     rules:
       - DOMAIN-SUFFIX,example.com,ProxyGroup
       - MATCH,DIRECT
     ```

3. **保存并应用配置**：
   - **保存文件**：保存修改后的配置文件。
   - **重新加载配置**：在 Clash 客户端中重新加载配置或重启应用。

4. **验证代理效果**：
   - **测试 URL 访问**：访问不同的 URL，确保流量按照设置的规则通过代理或直接连接。
